CREATE USER "ebdemo" WITH PASSWORD 'omedbe';

CREATE DATABASE "ebdemo"
  WITH OWNER "root"
  ENCODING 'UTF8';

\c ebdemo

CREATE SCHEMA "ebdemo";

GRANT ALL PRIVILEGES ON DATABASE "ebdemo"
TO "ebdemo";

CREATE TABLE "ebdemo"."fact" (
    n INT PRIMARY KEY,
    factorial TEXT,
    hits INT );

GRANT ALL PRIVILEGES ON SCHEMA "ebdemo" TO "ebdemo";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "ebdemo" TO "ebdemo";
ALTER DEFAULT PRIVILEGES IN SCHEMA "ebdemo" GRANT ALL PRIVILEGES ON TABLES  TO "ebdemo";
